import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/dashboard.tsx"),
  route("login", "routes/login.tsx"),
  route("users", "routes/users.tsx"),
  route("partner-users", "routes/partner-users.tsx"),
  route("partner-users/new", "routes/partner-users/new.tsx"),
  route("partner-users/:id", "routes/partner-users/$id.tsx"),
  route("api/partner-users", "routes/api.partner-users.tsx"),
  route("api/partner-users/:id", "routes/api.partner-users.$id.tsx"),
  route("api/companies", "routes/api.companies.tsx"),
  route("assignments", "routes/assignments.tsx"),
  route("dissertations", "routes/dissertations.tsx"),
  route("outreach-orders", "routes/outreach-orders.tsx"),
  route("outreach", "routes/outreach.tsx"),
  route("careers", "routes/careers.tsx"),
  route("settings", "routes/settings.tsx"),
  route("api/settings", "routes/api.settings.tsx"),
  route("email-sequences", "routes/email-sequences.tsx"),
  route("chat-logs", "routes/chat-logs.tsx"),
  route("api/chat-logs", "routes/api.chat-logs.tsx"),
  route("analytics", "routes/analytics.tsx"),
  route("utm-builder", "routes/utm-builder.tsx"),
  route("api/utm-campaigns", "routes/api.utm-campaigns.tsx"),
  route("api/posthog", "routes/api.posthog.tsx"),
  route("api/analytics", "routes/api.analytics.tsx"),
  route("api/outreach", "routes/api.outreach.tsx"),
] satisfies RouteConfig;

