import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/dashboard.tsx"),
  route("login", "routes/login.tsx"),
  route("users", "routes/users.tsx"),
  route("funnel", "routes/funnel.tsx"),
  route("assignments", "routes/assignments.tsx"),
  route("dissertations", "routes/dissertations.tsx"),
  route("outreach-orders", "routes/outreach-orders.tsx"),
  route("campaign-health", "routes/campaign-health.tsx"),
  route("paid-users", "routes/paid-users.tsx"),
  route("outreach-campaign", "routes/outreach-campaign.tsx"),
  route("outreach", "routes/outreach.tsx"),
  route("careers", "routes/careers.tsx"),
  route("settings", "routes/settings.tsx"),
  route("api/settings", "routes/api.settings.tsx"),
  route("email-sequences", "routes/email-sequences.tsx"),
  route("chat-logs", "routes/chat-logs.tsx"),
  route("api/chat-logs", "routes/api.chat-logs.tsx"),
  route("ops-alerts", "routes/ops-alerts.tsx"),
  route("api/ops-alerts", "routes/api.ops-alerts.tsx"),
  route("api/ops-alerts/:id", "routes/api.ops-alerts.$id.tsx"),
  route("tickets", "routes/tickets.tsx"),
  route("tickets/:id", "routes/tickets.$id.tsx"),
  route("api/tickets", "routes/api.tickets.tsx"),
  route("api/tickets/:id", "routes/api.tickets.$id.tsx"),
  route("api/tickets/:id/messages", "routes/api.tickets.$id.messages.tsx"),
  route("consultation-signups", "routes/consultation-signups.tsx"),
  route("api/consultation-signups", "routes/api.consultation-signups.tsx"),
  route("analytics", "routes/analytics.tsx"),
  route("utm-builder", "routes/utm-builder.tsx"),
  route("api/utm-campaigns", "routes/api.utm-campaigns.tsx"),
  route("coupons", "routes/coupons.tsx"),
  route("api/coupons", "routes/api.coupons.tsx"),
  route("api/posthog", "routes/api.posthog.tsx"),
  route("api/analytics", "routes/api.analytics.tsx"),
  route("api/outreach", "routes/api.outreach.tsx"),
  route("career-coach", "routes/career-coach.tsx"),
  route("webinar-registrations", "routes/webinar-registrations.tsx"),
  route("api/webinar-registrations", "routes/api.webinar-registrations.tsx"),
] satisfies RouteConfig;

