// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/funnel": {
    params: {};
  };
  "/journeys": {
    params: {};
  };
  "/daily": {
    params: {};
  };
  "/api/dashboard": {
    params: {};
  };
  "/api/overview": {
    params: {};
  };
  "/api/paid-emails": {
    params: {};
  };
  "/assignments": {
    params: {};
  };
  "/dissertations": {
    params: {};
  };
  "/outreach-orders": {
    params: {};
  };
  "/campaign-health": {
    params: {};
  };
  "/paid-users": {
    params: {};
  };
  "/outreach-campaign": {
    params: {};
  };
  "/outreach": {
    params: {};
  };
  "/careers": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/api/settings": {
    params: {};
  };
  "/email-sequences": {
    params: {};
  };
  "/chat-logs": {
    params: {};
  };
  "/api/chat-logs": {
    params: {};
  };
  "/ops-alerts": {
    params: {};
  };
  "/api/ops-alerts": {
    params: {};
  };
  "/api/ops-alerts/:id": {
    params: {
      "id": string;
    };
  };
  "/tickets": {
    params: {};
  };
  "/tickets/:id": {
    params: {
      "id": string;
    };
  };
  "/api/tickets": {
    params: {};
  };
  "/api/tickets/:id": {
    params: {
      "id": string;
    };
  };
  "/api/tickets/:id/messages": {
    params: {
      "id": string;
    };
  };
  "/consultation-signups": {
    params: {};
  };
  "/api/consultation-signups": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/utm-builder": {
    params: {};
  };
  "/api/utm-campaigns": {
    params: {};
  };
  "/coupons": {
    params: {};
  };
  "/api/coupons": {
    params: {};
  };
  "/api/posthog": {
    params: {};
  };
  "/api/analytics": {
    params: {};
  };
  "/api/outreach": {
    params: {};
  };
  "/career-coach": {
    params: {};
  };
  "/webinar-registrations": {
    params: {};
  };
  "/api/webinar-registrations": {
    params: {};
  };
  "/b2b-gtm": {
    params: {};
  };
  "/b2b-gtm/:id": {
    params: {
      "id": string;
    };
  };
  "/api/b2b-gtm": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/users" | "/funnel" | "/journeys" | "/daily" | "/api/dashboard" | "/api/overview" | "/api/paid-emails" | "/assignments" | "/dissertations" | "/outreach-orders" | "/campaign-health" | "/paid-users" | "/outreach-campaign" | "/outreach" | "/careers" | "/settings" | "/api/settings" | "/email-sequences" | "/chat-logs" | "/api/chat-logs" | "/ops-alerts" | "/api/ops-alerts" | "/api/ops-alerts/:id" | "/tickets" | "/tickets/:id" | "/api/tickets" | "/api/tickets/:id" | "/api/tickets/:id/messages" | "/consultation-signups" | "/api/consultation-signups" | "/analytics" | "/utm-builder" | "/api/utm-campaigns" | "/coupons" | "/api/coupons" | "/api/posthog" | "/api/analytics" | "/api/outreach" | "/career-coach" | "/webinar-registrations" | "/api/webinar-registrations" | "/b2b-gtm" | "/b2b-gtm/:id" | "/api/b2b-gtm";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/funnel.tsx": {
    id: "routes/funnel";
    page: "/funnel";
  };
  "routes/user-journeys.tsx": {
    id: "routes/user-journeys";
    page: "/journeys";
  };
  "routes/daily-dashboard.tsx": {
    id: "routes/daily-dashboard";
    page: "/daily";
  };
  "routes/api.dashboard.tsx": {
    id: "routes/api.dashboard";
    page: "/api/dashboard";
  };
  "routes/api.overview.tsx": {
    id: "routes/api.overview";
    page: "/api/overview";
  };
  "routes/api.paid-emails.tsx": {
    id: "routes/api.paid-emails";
    page: "/api/paid-emails";
  };
  "routes/assignments.tsx": {
    id: "routes/assignments";
    page: "/assignments";
  };
  "routes/dissertations.tsx": {
    id: "routes/dissertations";
    page: "/dissertations";
  };
  "routes/outreach-orders.tsx": {
    id: "routes/outreach-orders";
    page: "/outreach-orders";
  };
  "routes/campaign-health.tsx": {
    id: "routes/campaign-health";
    page: "/campaign-health";
  };
  "routes/paid-users.tsx": {
    id: "routes/paid-users";
    page: "/paid-users";
  };
  "routes/outreach-campaign.tsx": {
    id: "routes/outreach-campaign";
    page: "/outreach-campaign";
  };
  "routes/outreach.tsx": {
    id: "routes/outreach";
    page: "/outreach";
  };
  "routes/careers.tsx": {
    id: "routes/careers";
    page: "/careers";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/api.settings.tsx": {
    id: "routes/api.settings";
    page: "/api/settings";
  };
  "routes/email-sequences.tsx": {
    id: "routes/email-sequences";
    page: "/email-sequences";
  };
  "routes/chat-logs.tsx": {
    id: "routes/chat-logs";
    page: "/chat-logs";
  };
  "routes/api.chat-logs.tsx": {
    id: "routes/api.chat-logs";
    page: "/api/chat-logs";
  };
  "routes/ops-alerts.tsx": {
    id: "routes/ops-alerts";
    page: "/ops-alerts";
  };
  "routes/api.ops-alerts.tsx": {
    id: "routes/api.ops-alerts";
    page: "/api/ops-alerts";
  };
  "routes/api.ops-alerts.$id.tsx": {
    id: "routes/api.ops-alerts.$id";
    page: "/api/ops-alerts/:id";
  };
  "routes/tickets.tsx": {
    id: "routes/tickets";
    page: "/tickets";
  };
  "routes/tickets.$id.tsx": {
    id: "routes/tickets.$id";
    page: "/tickets/:id";
  };
  "routes/api.tickets.tsx": {
    id: "routes/api.tickets";
    page: "/api/tickets";
  };
  "routes/api.tickets.$id.tsx": {
    id: "routes/api.tickets.$id";
    page: "/api/tickets/:id";
  };
  "routes/api.tickets.$id.messages.tsx": {
    id: "routes/api.tickets.$id.messages";
    page: "/api/tickets/:id/messages";
  };
  "routes/consultation-signups.tsx": {
    id: "routes/consultation-signups";
    page: "/consultation-signups";
  };
  "routes/api.consultation-signups.tsx": {
    id: "routes/api.consultation-signups";
    page: "/api/consultation-signups";
  };
  "routes/analytics.tsx": {
    id: "routes/analytics";
    page: "/analytics";
  };
  "routes/utm-builder.tsx": {
    id: "routes/utm-builder";
    page: "/utm-builder";
  };
  "routes/api.utm-campaigns.tsx": {
    id: "routes/api.utm-campaigns";
    page: "/api/utm-campaigns";
  };
  "routes/coupons.tsx": {
    id: "routes/coupons";
    page: "/coupons";
  };
  "routes/api.coupons.tsx": {
    id: "routes/api.coupons";
    page: "/api/coupons";
  };
  "routes/api.posthog.tsx": {
    id: "routes/api.posthog";
    page: "/api/posthog";
  };
  "routes/api.analytics.tsx": {
    id: "routes/api.analytics";
    page: "/api/analytics";
  };
  "routes/api.outreach.tsx": {
    id: "routes/api.outreach";
    page: "/api/outreach";
  };
  "routes/career-coach.tsx": {
    id: "routes/career-coach";
    page: "/career-coach";
  };
  "routes/webinar-registrations.tsx": {
    id: "routes/webinar-registrations";
    page: "/webinar-registrations";
  };
  "routes/api.webinar-registrations.tsx": {
    id: "routes/api.webinar-registrations";
    page: "/api/webinar-registrations";
  };
  "routes/b2b-gtm.tsx": {
    id: "routes/b2b-gtm";
    page: "/b2b-gtm";
  };
  "routes/b2b-gtm.$id.tsx": {
    id: "routes/b2b-gtm.$id";
    page: "/b2b-gtm/:id";
  };
  "routes/api.b2b-gtm.tsx": {
    id: "routes/api.b2b-gtm";
    page: "/api/b2b-gtm";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/users": typeof import("./app/routes/users.tsx");
  "routes/funnel": typeof import("./app/routes/funnel.tsx");
  "routes/user-journeys": typeof import("./app/routes/user-journeys.tsx");
  "routes/daily-dashboard": typeof import("./app/routes/daily-dashboard.tsx");
  "routes/api.dashboard": typeof import("./app/routes/api.dashboard.tsx");
  "routes/api.overview": typeof import("./app/routes/api.overview.tsx");
  "routes/api.paid-emails": typeof import("./app/routes/api.paid-emails.tsx");
  "routes/assignments": typeof import("./app/routes/assignments.tsx");
  "routes/dissertations": typeof import("./app/routes/dissertations.tsx");
  "routes/outreach-orders": typeof import("./app/routes/outreach-orders.tsx");
  "routes/campaign-health": typeof import("./app/routes/campaign-health.tsx");
  "routes/paid-users": typeof import("./app/routes/paid-users.tsx");
  "routes/outreach-campaign": typeof import("./app/routes/outreach-campaign.tsx");
  "routes/outreach": typeof import("./app/routes/outreach.tsx");
  "routes/careers": typeof import("./app/routes/careers.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/api.settings": typeof import("./app/routes/api.settings.tsx");
  "routes/email-sequences": typeof import("./app/routes/email-sequences.tsx");
  "routes/chat-logs": typeof import("./app/routes/chat-logs.tsx");
  "routes/api.chat-logs": typeof import("./app/routes/api.chat-logs.tsx");
  "routes/ops-alerts": typeof import("./app/routes/ops-alerts.tsx");
  "routes/api.ops-alerts": typeof import("./app/routes/api.ops-alerts.tsx");
  "routes/api.ops-alerts.$id": typeof import("./app/routes/api.ops-alerts.$id.tsx");
  "routes/tickets": typeof import("./app/routes/tickets.tsx");
  "routes/tickets.$id": typeof import("./app/routes/tickets.$id.tsx");
  "routes/api.tickets": typeof import("./app/routes/api.tickets.tsx");
  "routes/api.tickets.$id": typeof import("./app/routes/api.tickets.$id.tsx");
  "routes/api.tickets.$id.messages": typeof import("./app/routes/api.tickets.$id.messages.tsx");
  "routes/consultation-signups": typeof import("./app/routes/consultation-signups.tsx");
  "routes/api.consultation-signups": typeof import("./app/routes/api.consultation-signups.tsx");
  "routes/analytics": typeof import("./app/routes/analytics.tsx");
  "routes/utm-builder": typeof import("./app/routes/utm-builder.tsx");
  "routes/api.utm-campaigns": typeof import("./app/routes/api.utm-campaigns.tsx");
  "routes/coupons": typeof import("./app/routes/coupons.tsx");
  "routes/api.coupons": typeof import("./app/routes/api.coupons.tsx");
  "routes/api.posthog": typeof import("./app/routes/api.posthog.tsx");
  "routes/api.analytics": typeof import("./app/routes/api.analytics.tsx");
  "routes/api.outreach": typeof import("./app/routes/api.outreach.tsx");
  "routes/career-coach": typeof import("./app/routes/career-coach.tsx");
  "routes/webinar-registrations": typeof import("./app/routes/webinar-registrations.tsx");
  "routes/api.webinar-registrations": typeof import("./app/routes/api.webinar-registrations.tsx");
  "routes/b2b-gtm": typeof import("./app/routes/b2b-gtm.tsx");
  "routes/b2b-gtm.$id": typeof import("./app/routes/b2b-gtm.$id.tsx");
  "routes/api.b2b-gtm": typeof import("./app/routes/api.b2b-gtm.tsx");
};